var annotated_dup =
[
    [ "NimBLE2904", "class_nim_b_l_e2904.html", "class_nim_b_l_e2904" ],
    [ "NimBLEAddress", "class_nim_b_l_e_address.html", "class_nim_b_l_e_address" ],
    [ "NimBLEAdvertisedDevice", "class_nim_b_l_e_advertised_device.html", "class_nim_b_l_e_advertised_device" ],
    [ "NimBLEAdvertisementData", "class_nim_b_l_e_advertisement_data.html", "class_nim_b_l_e_advertisement_data" ],
    [ "NimBLEAdvertising", "class_nim_b_l_e_advertising.html", "class_nim_b_l_e_advertising" ],
    [ "NimBLEAttribute", "class_nim_b_l_e_attribute.html", "class_nim_b_l_e_attribute" ],
    [ "NimBLEAttValue", "class_nim_b_l_e_att_value.html", "class_nim_b_l_e_att_value" ],
    [ "NimBLEBeacon", "class_nim_b_l_e_beacon.html", "class_nim_b_l_e_beacon" ],
    [ "NimBLECharacteristic", "class_nim_b_l_e_characteristic.html", "class_nim_b_l_e_characteristic" ],
    [ "NimBLECharacteristicCallbacks", "class_nim_b_l_e_characteristic_callbacks.html", "class_nim_b_l_e_characteristic_callbacks" ],
    [ "NimBLEClient", "class_nim_b_l_e_client.html", "class_nim_b_l_e_client" ],
    [ "NimBLEClientCallbacks", "class_nim_b_l_e_client_callbacks.html", "class_nim_b_l_e_client_callbacks" ],
    [ "NimBLEConnInfo", "class_nim_b_l_e_conn_info.html", "class_nim_b_l_e_conn_info" ],
    [ "NimBLEDescriptor", "class_nim_b_l_e_descriptor.html", "class_nim_b_l_e_descriptor" ],
    [ "NimBLEDescriptorCallbacks", "class_nim_b_l_e_descriptor_callbacks.html", "class_nim_b_l_e_descriptor_callbacks" ],
    [ "NimBLEDevice", "class_nim_b_l_e_device.html", null ],
    [ "NimBLEEddystoneTLM", "class_nim_b_l_e_eddystone_t_l_m.html", "class_nim_b_l_e_eddystone_t_l_m" ],
    [ "NimBLEEddystoneURL", "class_nim_b_l_e_eddystone_u_r_l.html", "class_nim_b_l_e_eddystone_u_r_l" ],
    [ "NimBLEExtAdvertisement", "class_nim_b_l_e_ext_advertisement.html", "class_nim_b_l_e_ext_advertisement" ],
    [ "NimBLEExtAdvertising", "class_nim_b_l_e_ext_advertising.html", "class_nim_b_l_e_ext_advertising" ],
    [ "NimBLEExtAdvertisingCallbacks", "class_nim_b_l_e_ext_advertising_callbacks.html", "class_nim_b_l_e_ext_advertising_callbacks" ],
    [ "NimBLEHIDDevice", "class_nim_b_l_e_h_i_d_device.html", "class_nim_b_l_e_h_i_d_device" ],
    [ "NimBLELocalAttribute", "class_nim_b_l_e_local_attribute.html", "class_nim_b_l_e_local_attribute" ],
    [ "NimBLERemoteCharacteristic", "class_nim_b_l_e_remote_characteristic.html", "class_nim_b_l_e_remote_characteristic" ],
    [ "NimBLERemoteDescriptor", "class_nim_b_l_e_remote_descriptor.html", "class_nim_b_l_e_remote_descriptor" ],
    [ "NimBLERemoteService", "class_nim_b_l_e_remote_service.html", "class_nim_b_l_e_remote_service" ],
    [ "NimBLEScan", "class_nim_b_l_e_scan.html", "class_nim_b_l_e_scan" ],
    [ "NimBLEScanCallbacks", "class_nim_b_l_e_scan_callbacks.html", "class_nim_b_l_e_scan_callbacks" ],
    [ "NimBLEScanResults", "class_nim_b_l_e_scan_results.html", "class_nim_b_l_e_scan_results" ],
    [ "NimBLEServer", "class_nim_b_l_e_server.html", "class_nim_b_l_e_server" ],
    [ "NimBLEServerCallbacks", "class_nim_b_l_e_server_callbacks.html", "class_nim_b_l_e_server_callbacks" ],
    [ "NimBLEService", "class_nim_b_l_e_service.html", "class_nim_b_l_e_service" ],
    [ "NimBLETaskData", "struct_nim_b_l_e_task_data.html", "struct_nim_b_l_e_task_data" ],
    [ "NimBLEUtils", "class_nim_b_l_e_utils.html", null ],
    [ "NimBLEUUID", "class_nim_b_l_e_u_u_i_d.html", "class_nim_b_l_e_u_u_i_d" ]
];