#ifndef _NRF52810CFG_H
#define _NRF52810CFG_H

#if !defined(NRF52810_XXAA)
# error NRF52810_XXAA not defined
#else

# ifndef MYNEWT_VAL_MCU_TARGET__nRF52810
#  define MYNEWT_VAL_MCU_TARGET__nRF52810 (1)
# endif

# ifndef MYNEWT_VAL_BLE_MAX_CONNECTIONS
#  define MYNEWT_VAL_BLE_MAX_CONNECTIONS 1
# endif

# ifndef MYNEWT_VAL_MSYS_1_BLOCK_COUNT
#  define MYNEWT_VAL_MSYS_1_BLOCK_COUNT (8)
# endif

# ifndef MYNEWT_VAL_MSYS_1_BLOCK_SIZE
#  define MYNEWT_VAL_MSYS_1_BLOCK_SIZE (88)
# endif

# ifndef MYNEWT_VAL_BLE_STORE_MAX_BONDS
#  define MYNEWT_VAL_BLE_STORE_MAX_BONDS 1
# endif

# if MYNEWT_VAL_BLE_STORE_MAX_BONDS
#  ifndef MYNEWT_VAL_BLE_STORE_MAX_CCCDS
#   define MYNEWT_VAL_BLE_STORE_MAX_CCCDS 3
#  endif
#  ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY
#   define MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY (1)
#  endif
# else
#  define MYNEWT_VAL_BLE_STORE_MAX_CCCDS 0
#  ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY
#   define MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY (0)
#  endif
# endif

# ifndef MYNEWT_VAL_BLE_ATT_PREFERRED_MTU
#  define MYNEWT_VAL_BLE_ATT_PREFERRED_MTU (256)
# endif

# ifndef MYNEWT_VAL_NIMBLE_HOST_TASK_STACK_SIZE
#  define MYNEWT_VAL_NIMBLE_HOST_TASK_STACK_SIZE (1408)
# endif

# ifndef MYNEWT_VAL_NIMBLE_CONTROLLER_TASK_STACK_SIZE
#  define MYNEWT_VAL_NIMBLE_CONTROLLER_TASK_STACK_SIZE (400)
# endif

# ifndef MYNEWT_VAL_BLE_SM_SC
#  define MYNEWT_VAL_BLE_SM_SC (0)
# endif

#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_CODED_PHY (0)

#endif // NRF52810_XXAA
#endif // _NRF52810CFG_H
